### ISSUE TITLE
Dalton on-premise release

### ISSUE THREAD

**Issue by clopmz** [secureworks/dalton#138]
Good morning,

 Are there any plans to release a version for deployment in on-premise or virtualization environments?

Regards

**Comment by whartond** [comment]
Dalton is just software and can be installed wherever you like (within reason).  Its current form makes it easy since the system can be built as a set of Docker containers which can be done wherever there is a docker engine, including on bare metal (commodity or appliance-grade hardware), virtual machines (including virtual machines running virtual machines), and the cloud.  I've run it on all those.

For simple instructions on a quick install in AWS see https://github.com/secureworks/dalton/blob/master/INSTALL-AWS.rst
