### ISSUE TITLE
API endpoint to submit a job

### ISSUE THREAD

**Issue by mundruid** [secureworks/dalton#157]
This is a TODO in the dalton controller: https://github.com/secureworks/dalton/blob/master/app/dalton.py#L1245.

### Environment
* Python version:  3.10.X

### Proposed Functionality

An API endpoint that accepts a set of pcaps and submits a job to dalton controller.

### Use Case

Automation for job submission.

If this is approved, I will be happy to work on the issue and submit a PR within a few weeks. Please feel free to assign it to me.

**Comment by dc-secureworks** [comment]
Hi Dr. X.  Thanks for the nudge on that TODO.  We might be able to implement it soon.  Good timing on that comment.  :)

**Comment by mundruid** [comment]
Cool, thanks for the response! Let me know if you need any help.

**Comment by whartond** [comment]
What do you envision such an API endpoint to look like?

Currently, programmatic submissions are possible, they just have to mimic a web submission (HTTP POST to `/dalton/coverage/summary`) where the components of the job (pcaps, config, custom rules, etc.) and submitted as a form post.  When doing such a submission, you'll want to set the `teapotJob` variable. That will cause the job submission to return the jobid(s) (instead of a redirect designed for a web browser) that can then be used to query the Dalton API for the job status and pull results; see https://github.com/secureworks/dalton/#teapot-jobs and https://github.com/secureworks/dalton/#dalton-api.

To see the HTTP format of a submission, use an intercepting proxy like BurpSuite or do a packet capture to sniff the traffic (assuming, in the later case, HTTPS is not being used).

As far as an improved submission API endpoint, it could be argued that having one that basically just accepts a compressed (zip, gz, etc) file containing the job components would be cleaner.  But I'm not convinced that, when it comes down to it, it would be that much less work building a client for it.

It may be worthwhile publishing an example script showing how to build the HTTP request for a job and/or detailing the different parameters used in job submission.

**Comment by mundruid** [comment]
@whartond, thanks for the response! I think it is a great idea to add a script. I had not deciphered what you said in your comment from the current documentation.

I have a PR with a sample script and some additions in documentation: https://github.com/secureworks/dalton/pull/158

I look forward to your comments!

**Comment by eatinsundip** [comment]
I am also highly interested in this feature. I am looking to pull PCAPs from outside sandbox sources and pump them through Dalton to speed up the process of finding malware that isn't currently being alerted on by popular open IDS lists.

**Comment by 0x120102181f0a040a01181c** [comment]
Added in #158.
