### ISSUE TITLE
update dockerfile_snort and dockerfile_suricata to newer ubuntu

### ISSUE THREAD

**Issue by rkoumis** [secureworks/dalton#199]
currently, both start with `FROM ubuntu:18.04`

Ubuntu 18.04 is no longer supported

We should use 24.04 or 22.04

**Comment by unusualevent** [comment]
that test by @da_667 is awesome!

**Comment by da667** [comment]
I'm not the best at git, and didn't realize my testing for cyberchef would carry into the pull request I've made. I've since created a new branch with both ubuntu 24.04 containers _and_ cyberchef, and have edited the master branch to remove the cyberchef changes I've proposed.

forked branch with cyberchef support: https://github.com/da667/dalton/tree/with-cyberchef-support
master fork: github.com/da667/dalton

**Comment by rkoumis** [comment]
Closing with #234
