### ISSUE TITLE
Fix Suricata rules Download links

### ISSUE THREAD

**Issue by Zer0d0y** [secureworks/dalton#77]
#### Hello,
From:https://github.com/secureworks/dalton/blob/master/app/dalton.py#L124
```shell
Link: https://rules.emergingthreats.net/open/suricata-1.3/emerging.rules.tar.gz

should be: https://rules.emergingthreats.net/open/suricata-4.0.0/emerging.rules.tar.gz
```

**this** [link](https://rules.emergingthreats.net/open/suricata-1.3/emerging.rules.tar.gz) not working

**Comment by counterthreatunit** [comment]
Thanks.  This functionality and download is provided as a convenience so that there are rulesets when someone starts up Dalton for the first time.  Ultimately, users should be populating and curating the rulesets according to their needs; see https://github.com/secureworks/dalton#adding-rulesets.

I'll update to use the suricata-2.0 ruleset since that is the new lowest common denominator. See #78
