### ISSUE TITLE
Install through a proxy...

### ISSUE THREAD

**Issue by kudude703** [secureworks/dalton#80]
Hello, 
I'm trying to run the install through a proxy.  My current environment has the internet completely blocked.  The proxy option in the README works only for apt-get and doesnt apply to the install process.

Thanks,

**Comment by counterthreatunit** [comment]
If you are installing in an environment that is behind a proxy, you will have to configure docker on the host in order to pull the images for ubuntu, redis, nginx, etc.  How exactly to do this can depend on host OS but typically it involves creating/editing `/etc/default/docker` or, if the host uses systemd, creating/editing `/etc/systemd/system/docker.service.d/http-proxy.conf`.  After the appropriate changes are made, docker will need to be restarted.

Ones the images are downloaded, when the containers are built, they will need to access the Internet to do things like run apt-get.  That is when the environment variables set in the .env file come into play.

Let me encourage you to carefully re-read https://github.com/secureworks/dalton/blob/master/README.rst#building-behind-a-proxy.

If you still have trouble, at what point exactly is the problem occurring?  What error messages are you seeing?  What is the host OS that is running docker?

**Comment by kudude703** [comment]
thank you!! you answered my question.
